#!/bin/bash
# vim:et:ft=sh:sts=2:sw=2

PHP_SAPIS="apache2 cli"

APACHE_USER="www-data"

os_install() {
  apt-get install -y $*
}

### Update repository package info ###
prepare_system() {
  echo
  echo "============================="
  echo "    Updating Repositories    "
  echo "============================="
  echo

  apt-get update -y
}

### PHP / PPA ###

install_php_core () {
  apt-get install -y python-software-properties
  add-apt-repository -y ppa:ondrej/php5
  apt-get update && apt-get upgrade -y
  apt-get install -y php5
}


### Extensions: Packages and PECL ###


install_pecl_http () {
  apt-get install -y libcurl3 libcurl4-gnutls-dev
  printf "\n\n\n\n" | pecl install pecl_http || true  # We need to "accept" the prompts.
  echo extension=http.so > /etc/php5/mods-available/http.ini
  php5enmod http
}

install_pecl_rrd () {
  apt-get install -y librrd-dev
  pecl install rrd || true
  echo extension=rrd.so > /etc/php5/mods-available/rrd.ini
  php5enmod rrd
}

install_pecl_yaml () {
  apt-get install -y libyaml-dev
  printf "\n" | pecl install yaml || true
  echo extension=yaml.so > /etc/php5/mods-available/yaml.ini
  php5enmod yaml
}

install_pecl_ssh () {
  apt-get install -y libssh2-1-dev
  printf "\n" | pecl install ssh2-beta || true
  echo extension=ssh2.so > /etc/php5/mods-available/ssh2.ini
  php5enmod ssh2
}

install_pecl_shared () {
  apt-get install -y build-essential php5-dev libmagic-dev php-pear
}

install_php_extension_pecls () {
  install_pecl_shared
  install_pecl_ssh
  install_pecl_rrd
  install_pecl_yaml
  install_pecl_http
}

install_php_extension_packages () {
  apt-get install -y php5-mysql php5-curl php-pear php5-mcrypt php5-snmp
}


### PHP CONFIGURATION OPTIONS ###

configure_php () {
  for sapi in $PHP_SAPIS
  do
    echo "Removing disabled functions for $sapi"
    sed -i '/^disable_functions/d' /etc/php5/$sapi/php.ini
    echo "Enabling short open tags for $sapi"
    sed -i -r 's/short_open_tag = .+/short_open_tag = On/g' /etc/php5/$sapi/php.ini
    # Set the timezone to the systems local time
    sed -i -r 's/;?date.timezone =.+/date.timezone = $(date +'%Z')"/g' /etc/php5/$sapi/php.ini
  done
  
}

pre_mysql_install () {
  echo mysql-server-5.5 mysql-server/root_password password $ROOT_MYSQL | debconf-set-selections
  echo mysql-server-5.5 mysql-server/root_password_again password $ROOT_MYSQL | debconf-set-selections
}

post_mysql_install() {
  : # Do nothing
}

pre_python_setup() {
  : # Do nothing
}

configure_rrdcached() {
  # Workaround for https://bugs.launchpad.net/ubuntu/+source/rrdtool/+bug/985341
  if [ "$DISTRIB_RELEASE" '=' "12.04" ]; then
    mkdir -p /var/lib/rrdcached/db /var/lib/rrdcached/journal
    chown $(printf %q "$USER"):$(printf %q "$(groups | awk '{print $1}')") /var/lib/rrdcached/db /var/lib/rrdcached/journal
  fi
  apt-get install -y rrdcached
  cat >> /etc/default/rrdcached << EOF
  OPTS="-s $SCALR_USER"
  OPTS="\$OPTS -l unix:/var/run/rrdcached.sock"
  OPTS="\$OPTS -j /var/lib/rrdcached/journal/ -F"
  OPTS="\$OPTS -b /var/lib/rrdcached/db/ -B"
EOF
}

set_apache_vars() {
  SCALR_SITE_PATH=/etc/apache2/sites-available/$SCALR_SITE_NAME
  SCALR_APACHE_GRANT="Require all granted"
}

configure_start_apache() {
  a2enmod rewrite

  # Disable all Apache default sites, however they're called
  a2dissite default || true
  a2dissite 000-default || true

  # Try adding our site, whichever configuration works
  a2ensite $SCALR_SITE_NAME || mv $SCALR_SITE_PATH $SCALR_SITE_PATH.conf && a2ensite $SCALR_SITE_NAME

  service apache2 restart
}


post_scalr_app_setup() {
  : # Do nothing
}

pre_init_setup() {
  : # Do nothing
}

configure_system() {
  echo "kernel.msgmnb = 524288" > /etc/sysctl.d/60-scalr.conf
  service procps start
}
